apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: demo-python-404046 
  janus-idp.io/tekton: demo-python-404046
  backstage.io/kubernetes-id: demo-python-404046
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: demo-python-404046
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml